# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: users
    - role: repo
      openio_repository_openstack_release: 'queens'
      openio_repository_no_log: false
      openio_repository_products:
        sds:
          release: "18.10"
    - role: gridinit
      openio_gridinit_per_ns: true
      openio_gridinit_namespace: "{{ NS }}"
    - role: role_under_test
      openio_ecd_namespace: "{{ NS }}"
...
